services:
  buddham_ai:
    image: buddham_ai:latest
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    runtime: nvidia               # เพิ่มให้ container ใช้ GPU
    environment:
      - NVIDIA_VISIBLE_DEVICES=all